// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from piggy.djinni

#pragma once

#include "djinni_support.hpp"
#include "server_message_getter.hpp"

namespace djinni_generated {

class NativeServerMessageGetter final : ::djinni::JniInterface<::ns_piggy_native::ServerMessageGetter, NativeServerMessageGetter> {
public:
    using CppType = std::shared_ptr<::ns_piggy_native::ServerMessageGetter>;
    using CppOptType = std::shared_ptr<::ns_piggy_native::ServerMessageGetter>;
    using JniType = jobject;

    using Boxed = NativeServerMessageGetter;

    ~NativeServerMessageGetter();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeServerMessageGetter>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeServerMessageGetter>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeServerMessageGetter();
    friend ::djinni::JniClass<NativeServerMessageGetter>;
    friend ::djinni::JniInterface<::ns_piggy_native::ServerMessageGetter, NativeServerMessageGetter>;

};

}  // namespace djinni_generated
