FROM ubuntu:bionic
RUN apt-get update && apt-get install -y sudo
RUN sudo apt-get install -y build-essential git \
    mysql-server mysql-client cmake autoconf libmysqlclient-dev libmysqld-dev \
    libmysql++-dev libmysql++-doc libmysql++3v5 libtool pkg-config automake \
    curl make g++ unzip wget zip zlib1g-dev python3 python && sudo apt-get clean
RUN wget https://github.com/bazelbuild/bazel/releases/download/0.29.0/bazel-0.29.0-installer-linux-x86_64.sh && chmod +x bazel-0.29.0-installer-linux-x86_64.sh && \
    ./bazel-0.29.0-installer-linux-x86_64.sh --user && export PATH="$PATH:$HOME/bin"
RUN export CC=gcc
COPY SingleLoginServer /single_login_src/SingleLoginServer/
RUN cd /single_login_src
RUN git clone https://github.com/trusch/libbcrypt
RUN cd /single_login_src/libbcrypt
RUN mkdir build && cd build && cmake .. && make && sudo make install && sudo ldconfig

RUN sudo service mysql restart
CMD [ "./single_login_src/SingleLoginServer/bazel-bin/examples/greeter_server" ]
